language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t lucasatmogree/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucasatmogree/react-test npm run test

after_success:
  - docker build -t lucasatmogree/complex-client -f ./client/Dockerfile ./client
  - docker build -t lucasatmogree/complex-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t lucasatmogree/complex-server -f ./server/Dockerfile ./server
  - docker build -t lucasatmogree/complex-worker -f ./client/Dockerfile ./worker
  - docker login --username "$DOCKER_ID" --password "$DOCKER_PASSWORD"
  - docker push lucasatmogree/complex-client
  - docker push lucasatmogree/complex-nginx
  - docker push lucasatmogree/complex-server
  - docker push lucasatmogree/complex-worker