language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t lucas-at-mogree/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucas-at-mogree/react-test npm run test

after_success:
  - docker build -t lucas-at-mogree/complex-client -f ./client/Dockerfile ./client
  - docker build -t lucas-at-mogree/complex-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t lucas-at-mogree/complex-server -f ./server/Dockerfile ./server
  - docker build -t lucas-at-mogree/complex-worker -f ./client/Dockerfile ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push lucas-at-mogree/complex-client
  - docker push lucas-at-mogree/complex-nginx
  - docker push lucas-at-mogree/complex-server
  - docker push lucas-at-mogree/complex-worker